name: asaxiy_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  get_it: ^7.6.0 # for DI
  get: ^4.6.5
  shimmer: ^3.0.0
  flutter_bloc: ^8.1.3 # like MVI
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.0
  firebase_core: ^2.15.1
  cached_network_image:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  smooth_page_indicator: ^1.1.0
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gif/
